#当前工作目录
getwd()
#设置工作目录，注意斜杠
setwd('C:/Users/24066/Desktop/药研社/三维散点图') 
#查看目录
dir()
#逗号分隔值CSV，blank.lines.skip跳过空白行，stringsAsFactors(T)字符型向量转换为因子
df<-read.csv('vb12.csv',header = TRUE,sep = ',',blank.lines.skip = FALSE,stringsAsFactors = FALSE)
#数据框前6行
head(df)
#df['DOSE_STD']数据和格式，df[['DOSE_STD']]只数据，df$DOSE_STD只数据
#df的2、4、5列组成新数据框
df<-df[c(2,4,5)]
names(df)<-c('DOSE_STD','VB12','HbA1c')
#attach()绑定对象，可直接调用变量；detach()解绑对象
attach(df)
install.packages('scatterplot3d')
library(scatterplot3d)
help(package='scatterplot3d')
#查看R版本
sessionInfo()

install.packages('rgl')
#报错:没有rlang包，安装R405解决
install.packages('rlang')
library(rgl)
plot3d(HbA1c,VB12,DOSE_STD,col='green',size=5)
#查看加载的包
(.packages())
